---
service: es-config-loader
provider:
  name: aws
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  memorySize: 1024
  timeout: 20
  tracing:
    lambda: true
  package:
    individually: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-error-handler:
    name: runtime_error_capture
    handler: runtime_error_capture.lambda_handler
    package:
      individually: true
      include:
        - runtime_error_capture.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-common-functions:latest
    tags:
      app: results
    environment:
      sns_topic_arn: arn:aws:sns:eu-west-2:014669633018:BMIResults

plugins:
  - serverless-latest-layer-version
